# Generated by Django 4.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Configuración')),
                ('email_host', models.CharField(max_length=200, verbose_name='Servidor SMTP')),
                ('email_port', models.IntegerField(default=587, verbose_name='Puerto SMTP')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='Usar SSL')),
                ('email_host_user', models.CharField(max_length=200, verbose_name='Usuario SMTP')),
                ('email_host_password', models.CharField(max_length=200, verbose_name='Contraseña SMTP')),
                ('default_from_email', models.EmailField(max_length=254, verbose_name='Email Remitente Por Defecto')),
                ('is_active', models.BooleanField(default=False, verbose_name='Configuración Activa')),
                ('test_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email para Pruebas')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración SMTP',
                'verbose_name_plural': 'Configuraciones SMTP',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]