# Generated by Django 4.2 on 2025-04-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usr_2fa',
            field=models.BooleanField(default=False, verbose_name='Autenticación de dos factores'),
        ),
    ]
