# Generated by Django 4.2 on 2025-04-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_data_user_2fa_transition'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usr_recovery_codes',
            field=models.TextField(blank=True, help_text='Códigos de recuperación para 2FA', null=True),
        ),
    ]
