# Generated by Django 4.2 on 2025-04-12 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan_cuentas', '0001_initial'),
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cuenta_debe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos_debe', to='plan_cuentas.plancuenta')),
                ('cuenta_haber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos_haber', to='plan_cuentas.plancuenta')),
                ('perfil_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos', to='perfiles.perfil')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
    ]
