# Generated by Django 4.2 on 2025-04-12 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_cuentas', '0002_alter_plancuenta_options_plancuenta_codigocuenta_and_more'),
        ('perfiles', '0002_alter_perfil_options_perfil_empresa_and_more'),
        ('asientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asiento',
            options={'ordering': ['-fecha'], 'verbose_name': 'Asiento Contable', 'verbose_name_plural': 'Asientos Contables'},
        ),
        migrations.AddField(
            model_name='asiento',
            name='empresa',
            field=models.CharField(default='DEFAULT', max_length=24),
        ),
        migrations.AddField(
            model_name='asiento',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfiles.perfil', verbose_name='Perfil Contable'),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='cuenta_debe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos_debe', to='plan_cuentas.plancuenta', verbose_name='Cuenta Debe'),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='cuenta_haber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos_haber', to='plan_cuentas.plancuenta', verbose_name='Cuenta Haber'),
        ),
        migrations.AlterUniqueTogether(
            name='asiento',
            unique_together={('empresa', 'fecha')},
        ),
        migrations.RemoveField(
            model_name='asiento',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='asiento',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='asiento',
            name='perfil_contable',
        ),
        migrations.RemoveField(
            model_name='asiento',
            name='usuario_creacion',
        ),
    ]
