# Generated by Django 4.2 on 2025-04-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asientos', '0002_alter_asiento_options_asiento_empresa_asiento_perfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asiento',
            name='cuenta_debe',
        ),
        migrations.RemoveField(
            model_name='asiento',
            name='cuenta_haber',
        ),
    ]
