# Generated by Django 4.2 on 2025-05-25 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asientos', '0003_remove_asiento_cuenta_debe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asiento',
            name='perfil',
        ),
    ]
