# Generated by Django 4.2 on 2025-06-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asientos', '0004_remove_asiento_perfil'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asiento',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='empresa',
            field=models.CharField(default='DEFAULT', max_length=24, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
