# Generated by Django 4.2
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_alter_perfil_id'),
        ('asientos', '0005_alter_asiento_unique_together_alter_asiento_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='id_perfil',
            field=models.ForeignKey(
                blank=True,
                db_column='id_perfil',
                help_text='Perfil contable asociado al asiento',
                null=True,
                on_delete=models.CASCADE,
                to='perfiles.perfil',
                verbose_name='Perfil'
            ),
        ),
    ] 