# Generated by Django 4.2 on 2025-09-02 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asientos', '0006_add_id_perfil_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del asiento contable', max_length=500, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha y hora cuando se creó el asiento', verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asiento',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el asiento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, help_text='Último usuario que modificó el asiento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
    ]
