version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --innodb-use-native-aio=0
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    env_file:
      - docker.env
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 1g

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    env_file:
      - docker.env
    depends_on:
      - db
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 2g

volumes:
  mysql_data:
  static_volume:
  media_volume:

networks:
  app-network:
    driver: bridge