# Generated by Django 4.2 on 2025-06-12 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureDataMatrix',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=128, unique=True)),
                ('data_type', models.CharField(choices=[('decoy', 'Información Falsa'), ('real', 'Información Real')], max_length=20)),
                ('row_index', models.IntegerField()),
                ('col_index', models.IntegerField()),
                ('encrypted_value', models.TextField()),
                ('encryption_salt', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dato Seguro',
                'verbose_name_plural': 'Datos Seguros',
                'ordering': ['password_hash', 'row_index', 'col_index'],
                'unique_together': {('password_hash', 'row_index', 'col_index')},
            },
        ),
        migrations.CreateModel(
            name='SecureAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('password_type', models.CharField(choices=[('decoy', 'Contraseña Falsa'), ('real', 'Contraseña Real')], max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('user_agent', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acceso Seguro',
                'verbose_name_plural': 'Logs de Acceso Seguro',
                'ordering': ['-access_time'],
            },
        ),
    ]
