# Generated by Django 4.2 on 2025-06-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securedatamatrix',
            name='password_hash',
            field=models.CharField(max_length=128),
        ),
    ]
