# Generated by Django 4.2 on 2025-06-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_data', '0002_remove_password_hash_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurePassword',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('password_text', models.CharField(max_length=100, unique=True, verbose_name='Contraseña Secreta')),
                ('password_hash', models.CharField(max_length=128, unique=True, verbose_name='Hash de la Contraseña')),
                ('password_type', models.CharField(choices=[('decoy', 'Información Falsa/Pública'), ('real', 'Información Real/Confidencial')], max_length=20, verbose_name='Tipo de Información')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contraseña Secreta',
                'verbose_name_plural': 'Contraseñas Secretas',
                'ordering': ['password_type', 'password_text'],
            },
        ),
    ]
