# Generated by Django 4.2 on 2025-06-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_data', '0003_add_secure_password_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securedatamatrix',
            name='col_index',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='securedatamatrix',
            name='row_index',
            field=models.BigIntegerField(),
        ),
    ]
