# Generated by Django 4.2 on 2025-06-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_data', '0004_alter_securedatamatrix_col_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securedatamatrix',
            name='row_index',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='securedatamatrix',
            name='col_index',
            field=models.BigIntegerField(),
        ),
    ]
