# Generated by Django 4.2.16 

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_data', '0005_auto_20250611_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='secureaccesslog',
            name='access_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Código de Acceso'),
        ),
        migrations.AddField(
            model_name='secureaccesslog',
            name='action',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Acción Realizada'),
        ),
        migrations.AddField(
            model_name='secureaccesslog',
            name='is_decoy_attempt',
            field=models.BooleanField(default=False, verbose_name='Intento con Señuelo'),
        ),
        migrations.AlterField(
            model_name='secureaccesslog',
            name='password_type',
            field=models.CharField(blank=True, choices=[('decoy', 'Contraseña Falsa'), ('real', 'Contraseña Real')], max_length=20, null=True),
        ),
    ]