# Generated by Django 4.2 on 2025-04-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['secuencial'], 'verbose_name': 'Perfil Contable', 'verbose_name_plural': 'Perfiles Contables'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='empresa',
            field=models.CharField(default='DEFAULT', max_length=24),
        ),
        migrations.AddField(
            model_name='perfil',
            name='secuencial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='vigencia',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='descripcion',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='perfil',
            unique_together={('empresa', 'secuencial')},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='usuario_creacion',
        ),
    ]
