# Generated by Django 4.2 on 2025-06-29 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_alter_perfil_id'),
    ]

    operations = [
        # Migración vacía para sincronizar el estado del modelo con la base de datos
        # Los campos nombre y descripcion ya existen en la tabla
    ]
