# Generated by Django 4.2 on 2025-05-07 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_cuentas', '0002_alter_plancuenta_options_plancuenta_codigocuenta_and_more'),
        ('perfiles', '0003_alter_perfil_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPlanCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(editable=False, help_text='Se deriva automáticamente del perfil seleccionado.', max_length=24)),
                ('polaridad', models.CharField(choices=[('+', 'Positiva (+ / Debe)'), ('-', 'Negativa (- / Haber)')], help_text="Define la naturaleza de la cuenta dentro del perfil (ej. '+' para Debe, '-' para Haber).", max_length=1, verbose_name='Polaridad')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_configurados', to='plan_cuentas.plancuenta', verbose_name='Cuenta Contable')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_configuradas', to='perfiles.perfil', verbose_name='Perfil Contable')),
            ],
            options={
                'verbose_name': 'Configuración de Cuenta en Perfil',
                'verbose_name_plural': 'Configuraciones de Cuentas en Perfiles',
                'ordering': ['empresa', 'perfil__secuencial', 'cuenta__codigocuenta'],
                'unique_together': {('empresa', 'perfil', 'cuenta')},
            },
        ),
    ]
