# Generated by Django 4.2 on 2025-06-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0004_auto_20250628_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['descripcion'], 'verbose_name': 'Perfil Contable', 'verbose_name_plural': 'Perfiles Contables'},
        ),
        migrations.AlterUniqueTogether(
            name='perfil',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='secuencial',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='vigencia',
        ),
    ]
