# Generated by Django 4.2 on 2025-06-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0006_alter_perfil_options_alter_perfilplancuenta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(max_length=64, verbose_name='Nombre del Perfil'),
        ),
    ]
