# Generated by Django 4.2 on 2025-07-07 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_cuentas', '0001_initial'),
        ('perfiles', '0007_alter_perfil_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPlanCuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(default='DEFAULT', max_length=24, verbose_name='Empresa')),
                ('polaridad', models.CharField(choices=[('+', 'Positiva (+ / Debe)'), ('-', 'Negativa (- / Haber)')], help_text="Define la naturaleza de la cuenta dentro del perfil (ej. '+' para Debe, '-' para Haber).", max_length=1, verbose_name='Polaridad')),
                ('cuentas_id', models.ForeignKey(db_column='cuenta_id', on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_configurados', to='plan_cuentas.cuenta', verbose_name='Cuenta Contable')),
                ('perfil_id', models.ForeignKey(db_column='perfil_id', on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_configuradas', to='perfiles.perfil', verbose_name='Perfil Contable')),
            ],
            options={
                'verbose_name': 'Configuración de Cuenta en Perfil',
                'verbose_name_plural': 'Configuraciones de Cuentas en Perfiles',
                'ordering': ['perfil_id__nombre', 'cuentas_id__descripcion'],
                'unique_together': {('perfil_id', 'cuentas_id')},
            },
        ),
    ]
