# Generated by Django 4.2 on 2025-02-21 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('asc_id', models.AutoField(primary_key=True, serialize=False)),
                ('asc_date', models.DateField()),
                ('asc_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asc_description', models.TextField()),
                ('asc_currency_type', models.CharField(max_length=3)),
                ('asc_transaction_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asc_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
