# Generated by Django 4.2 on 2025-02-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingentry',
            options={'verbose_name': 'Asiento Contable', 'verbose_name_plural': 'Asientos Contables'},
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='asc_currency_type',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], max_length=3),
        ),
    ]
