# Generated by Django 4.2 on 2025-02-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_alter_accountingentry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingentry',
            name='asc_currency_type',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], max_length=3),
        ),
    ]
