# Generated by Django 4.2 on 2025-07-07 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0008_perfilplancuenta'),
        ('empresas', '0003_alter_empresa_id'),
        ('plan_cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'ordering': ['plan_cuentas', 'cuenta'], 'verbose_name': 'Cuenta Contable', 'verbose_name_plural': 'Cuentas Contables'},
        ),
        migrations.AlterModelOptions(
            name='plancuenta',
            options={'ordering': ['empresa', 'descripcion'], 'verbose_name': 'Plan de Cuentas', 'verbose_name_plural': 'Planes de Cuentas'},
        ),
        migrations.RemoveConstraint(
            model_name='cuenta',
            name='plan_cuentas_cuenta_plan_cuentas_cuenta_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='plancuenta',
            name='plan_cuentas_plancuenta_empresa_grupo_uniq',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cuenta_madre',
            field=models.ForeignKey(blank=True, help_text='Cuenta padre en la jerarquía', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_hijas', to='plan_cuentas.cuenta', verbose_name='Cuenta Madre'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='grupo',
            field=models.IntegerField(blank=True, help_text='1=Activos, 2=Pasivos, 3=Patrimonio, 4=Ingresos, 5=Gastos', null=True, verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='cuenta',
            field=models.CharField(max_length=14, verbose_name='Código de Cuenta'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción de la Cuenta'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='plan_cuentas',
            field=models.ForeignKey(help_text='Plan de cuentas al que pertenece', on_delete=django.db.models.deletion.CASCADE, to='plan_cuentas.plancuenta', verbose_name='Plan de Cuentas'),
        ),
        migrations.AlterField(
            model_name='plancuenta',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción del Plan de Cuentas'),
        ),
        migrations.AlterField(
            model_name='plancuenta',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa a la que pertenece el plan de cuentas', on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='plancuenta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plancuenta',
            name='perfil',
            field=models.ForeignKey(db_column='perfil_id', help_text='Perfil contable asociado', on_delete=django.db.models.deletion.CASCADE, to='perfiles.perfil', verbose_name='Perfil'),
        ),
        migrations.AlterUniqueTogether(
            name='cuenta',
            unique_together={('plan_cuentas', 'cuenta')},
        ),
        migrations.AlterUniqueTogether(
            name='plancuenta',
            unique_together={('empresa', 'descripcion')},
        ),
        migrations.AlterModelTable(
            name='cuenta',
            table=None,
        ),
        migrations.AlterModelTable(
            name='plancuenta',
            table=None,
        ),
        migrations.RemoveField(
            model_name='plancuenta',
            name='grupo',
        ),
    ]
