# Generated by Django 4.2 on 2025-04-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plancuenta',
            options={'ordering': ['codigocuenta'], 'verbose_name': 'Cuenta Contable', 'verbose_name_plural': 'Plan de Cuentas'},
        ),
        migrations.AddField(
            model_name='plancuenta',
            name='codigocuenta',
            field=models.CharField(default='DEFAULT', max_length=14),
        ),
        migrations.AddField(
            model_name='plancuenta',
            name='cuentamadre',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='plancuenta',
            name='empresa',
            field=models.CharField(default='DEFAULT', max_length=24),
        ),
        migrations.AddField(
            model_name='plancuenta',
            name='grupo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plancuenta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='plancuenta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='plancuenta',
            unique_together={('empresa', 'grupo')},
        ),
        migrations.RemoveField(
            model_name='plancuenta',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='plancuenta',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='plancuenta',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='plancuenta',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='plancuenta',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='plancuenta',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='plancuenta',
            name='usuario_creacion',
        ),
    ]
