# Generated by Django 4.2 on 2025-05-07 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0004_perfilplancuenta'),
        ('plan_cuentas', '0002_alter_plancuenta_options_plancuenta_codigocuenta_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plancuenta',
            unique_together={('empresa', 'codigocuenta')},
        ),
        migrations.AddField(
            model_name='plancuenta',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_directas', to='perfiles.perfil', verbose_name='Perfil Contable Asociado'),
        ),
    ]
