# Generated by Django 4.2 on 2025-04-12 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('causa', models.TextField()),
                ('referencia_extra', models.TextField(blank=True, null=True)),
                ('monto_haber', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monto_debe', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('polaridad', models.CharField(choices=[('+', 'Positivo'), ('-', 'Negativo')], default='+', max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='asientos.asiento')),
            ],
            options={
                'verbose_name': 'Detalle de Asiento',
                'verbose_name_plural': 'Detalles de Asientos',
                'ordering': ['asiento', 'id'],
            },
        ),
    ]
