# Generated by Django 4.2 on 2025-04-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asientos_detalle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asientodetalle',
            options={'ordering': ['asiento'], 'verbose_name': 'Detalle de Asiento', 'verbose_name_plural': 'Detalles de Asientos'},
        ),
        migrations.RemoveField(
            model_name='asientodetalle',
            name='causa',
        ),
        migrations.RemoveField(
            model_name='asientodetalle',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='asientodetalle',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='asientodetalle',
            name='monto_debe',
        ),
        migrations.RemoveField(
            model_name='asientodetalle',
            name='monto_haber',
        ),
        migrations.RemoveField(
            model_name='asientodetalle',
            name='referencia_extra',
        ),
        migrations.AddField(
            model_name='asientodetalle',
            name='DetalleDeCausa',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='asientodetalle',
            name='Referencia',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='asientodetalle',
            name='cuenta',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='asientodetalle',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asientodetalle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='asientodetalle',
            name='polaridad',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
