# Generated by Django 4.2 on 2025-04-12 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asientos_detalle', '0002_alter_asientodetalle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asientodetalle',
            options={'ordering': ['asiento', 'tipo_cuenta'], 'verbose_name': 'Detalle de Asiento', 'verbose_name_plural': 'Detalles de Asientos'},
        ),
        migrations.AddField(
            model_name='asientodetalle',
            name='tipo_cuenta',
            field=models.CharField(choices=[('DEBE', 'Cuenta Debe'), ('HABER', 'Cuenta Haber')], default='DEBE', max_length=5, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AlterField(
            model_name='asientodetalle',
            name='DetalleDeCausa',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Causa'),
        ),
        migrations.AlterField(
            model_name='asientodetalle',
            name='Referencia',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Referencia Extra'),
        ),
        migrations.AlterField(
            model_name='asientodetalle',
            name='polaridad',
            field=models.CharField(blank=True, choices=[('+', 'Positivo'), ('-', 'Negativo')], max_length=1, null=True, verbose_name='Suma/Resta'),
        ),
        migrations.AlterField(
            model_name='asientodetalle',
            name='valor',
            field=models.FloatField(blank=True, null=True, verbose_name='Monto'),
        ),
    ]
