# Generated by Django 4.2 on 2025-05-07 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asientos_detalle', '0003_alter_asientodetalle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asientodetalle',
            options={'ordering': ['asiento', 'id'], 'verbose_name': 'Detalle de Asiento', 'verbose_name_plural': 'Detalles de Asientos'},
        ),
    ]
