# Generated by Django 4.2 on 2025-05-07 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_alter_perfil_id'),
        ('asientos_detalle', '0004_alter_asientodetalle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientodetalle',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_asiento', to='perfiles.perfil', verbose_name='Perfil del Detalle'),
        ),
    ]
