# Generated by Django 4.2 on 2025-05-07 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asientos_detalle', '0005_asientodetalle_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asientodetalle',
            name='perfil',
        ),
    ]
