# Generated by Django 4.2 on 2025-05-25 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_alter_perfil_id'),
        ('asientos_detalle', '0006_remove_asientodetalle_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientodetalle',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfiles.perfil', verbose_name='Perfil Contable'),
        ),
    ]
