# Generated by Django 4.2 on 2025-05-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asientos_detalle', '0007_asientodetalle_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asientodetalle',
            name='polaridad',
            field=models.CharField(choices=[('+', 'Positivo'), ('-', 'Negativo')], default='-', max_length=1, verbose_name='Suma/Resta'),
        ),
    ]
