# Generated by Django 4.2 on 2025-06-23 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asientos', '0005_alter_asiento_unique_together_alter_asiento_empresa_and_more'),
        ('asientos_detalle', '0008_alter_asientodetalle_polaridad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asientodetalle',
            name='perfil',
        ),
        migrations.AlterField(
            model_name='asientodetalle',
            name='DetalleDeCausa',
            field=models.CharField(blank=True, db_column='DetalleDeCausa', max_length=64, null=True, verbose_name='Detalle de Causa'),
        ),
        migrations.AlterField(
            model_name='asientodetalle',
            name='Referencia',
            field=models.CharField(blank=True, db_column='Referencia', max_length=45, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='asientodetalle',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='asientos.asiento', verbose_name='Asiento Contable'),
        ),
    ]
