# Generated by Django 4.2 on 2025-06-23 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asientos_detalle', '0009_remove_asientodetalle_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asientodetalle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asientodetalle',
            name='polaridad',
            field=models.CharField(choices=[('+', 'Positivo'), ('-', 'Negativo')], default='-', max_length=1, verbose_name='Polaridad'),
        ),
        migrations.AlterField(
            model_name='asientodetalle',
            name='valor',
            field=models.FloatField(blank=True, db_column='valor', null=True, verbose_name='Valor'),
        ),
    ]
