# Generated by Django 4.2 on 2025-06-29 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_empresa_id'),
        ('asientos_detalle', '0010_alter_asientodetalle_cuenta_alter_asientodetalle_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientodetalle',
            name='empresa_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa'),
        ),
    ]
