# Generated by Django 4.2 on 2025-07-07 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_cuentas', '0001_initial'),
        ('asientos_detalle', '0011_asientodetalle_empresa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asientodetalle',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos_detalles', to='plan_cuentas.cuenta', verbose_name='Cuenta Contable'),
        ),
    ]
