# Generated by Django 4.2 on 2025-06-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.CharField(help_text='Identificador único de la empresa (máximo 24 caracteres)', max_length=24, primary_key=True, serialize=False, verbose_name='ID Empresa')),
                ('type', models.CharField(blank=True, help_text='Tipo o clasificación de la empresa', max_length=50, null=True, verbose_name='Tipo de Empresa')),
                ('nombre', models.CharField(help_text='Nombre completo de la empresa', max_length=200, verbose_name='Nombre de la Empresa')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional de la empresa', null=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la empresa está activa en el sistema', verbose_name='¿Empresa Activa?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
    ]
